Remove vfork definition
This was causing clang to complain about the following:

include/mingw.h:488:7: error: incompatible redeclaration of library
function 'vfork'

Let's remove it as the MSYS2 Clang toolchain apparently has this
defined already.

Signed-off-by: Dennis Ameling <dennis@dennisameling.com>